# GitHub Action for generating a contribution graph with a snake eating your contributions ğŸ

name: Generate Snake

on:
  schedule:
    # her gÃ¼n gece 12'de Ã§alÄ±ÅŸÄ±r (istersen deÄŸiÅŸtir)
    - cron: "0 0 * * *"

  # manuel tetikleme iÃ§in
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # reponu checkout et
      - uses: actions/checkout@v4

      # snake SVG Ã¼ret
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: thesamata
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light

      # output branch'e deploy et (GitHub Pages iÃ§in)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
